<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE bank[
<!ELEMENT bank (account+)>
<!ELEMENT account (acc_no,branch_name,balance*)>
<!ELEMENT acc_no (#PCDATA)>
<!ELEMENT branch_name (#PCDATA)>
<!ELEMENT balance (#PCDATA)>
]>
<bank>
 <account>
 <acc_no>A-101</acc_no>
 <branch_name>DOWN TOWN</branch_name>
 </account>
 
 <account>
 <acc_no>A-102</acc_no>
 <branch_name>Perry ridge</branch_name>
 <balance>500</balance>
 </account>

 <account>
 <acc_no>A-103</acc_no>
 <branch_name>DOWN TOWN</branch_name>
 <balance>1000</balance>
 </account></bank>
